apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-demo-image
spec:
  containers:
    - name: my-demo
      image: my-demo-image:v1
      ports:
        - containerPort: 8080
    - name: postgres
      image: postgres:13
      ports:
        - containerPort: 5432