apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      name: postgres
      image: postgres:13
      ports:
        - containerPort: 80
      imagePullPolicy: Always